sonar.projectKey=ORION
sonar.projectName=ORION
sonar.sources=src,lib
sonar.exclusions=**/node_modules/**,**/dist/**,**/.expo/**,**/android/**,**/ios/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_1a779ca798c86dc8e3d76085ab03e50acca6581b
sonar.sourceEncoding=UTF-8